qase-tms/qasectl

internal/client/clientv1.go, internal/client/converterv1.go, internal/models/import/attachment.go, internal/models/import/data.go, internal/models/import/execution.go, internal/models/import/relation.go, internal/models/import/result.go, internal/models/import/step.go, internal/models/import/stepexecution.go, internal/models/import/suite.go, internal/models/import/suitedata.go, internal/parsers/junit/junit.go, internal/parsers/junit/models.go, internal/service/import/import.go
Added result models
--
These models describe the test result and will be used in internal logic
---
Extend the client
--
- added `UploadData` method to the client which uploads test results to the Qase.
- added a converter which converts internal models to APi models
- added base for import service
---
Added Junit XML parser
--
Added Junit XML parser which parses and converts Junit XML test result to internal models
=> Extend the client

cmd/root.go, cmd/testops/result/upload/upload.go, internal/client/converterv1.go, internal/parsers/xctest/models.go, internal/parsers/xctest/steplevel.go, internal/parsers/xctest/xctest.go
Added slog logger
--
Added slog logger and verbose parameter to all command. The parameter has two forms: `--verbose` and `-v`.
---
Added xctest parser
--
The parser can parse XCResult files to internal models. It also has additional parameter `steps`. This parameter manages how to convert steps.
---
Support upload attachments from strings in the client
---
Updated upload command
--
- support xctest results
- improve logs
- add `steps` parameter
=> Added xctest parser

cmd/testops/result/upload/upload.go, internal/client/clientv1.go, internal/service/result/models.go, internal/service/result/result.go
Added uploading of results in batch
--
- add new parameter `--batch` or `-b`. Default value is 200.
- improve logs in the result service
---
Improved logs in the client
---
Refactored result service.
--
Moved main logic from the command to the service.
=> Added uploading of results in batch

cmd/testops/result/upload/upload.go, cmd/testops/run/create/create.go, internal/client/clientv1.go, internal/models/run/environment.go, internal/service/result/models.go, internal/service/result/result.go, internal/service/run/run.go
clientv1: add get environment method and change signature of create test run method
---
run: add support environment
--
- add a new flag `environment`
- update internal logic of the run service
---
upload: update internal logic
--
- use the run service inside the upload service
- update `UploadParams` model
=> run: add support environment

cmd/testops/run/create/create.go, internal/client/clientv1.go, internal/models/run/environment.go, internal/models/run/models.go, internal/service/result/result.go, internal/service/run/run.go
clientv1: add new methods
--
- add `GetMilestones` method
- add `GetPlans` method
- update signature of the create test run method
- add `milestone` and `plan` models
---
run: add support plan and milestone
--
- add `plan` and `milestone` parameters
- update internal logic of the run service
---
upload: add support new signature of the run service
=> run: add support plan and milestone

.github/workflows/build-binaries.yml, Makefile
* On tag pushes, use the tag name;
* On commit pushes, use the commit's shortened SHA
* Build Docker images on every push event, but push to registry only
on git tag pushes.
* Make the build-docker-n-publish job dependent on `test` job and not
the other build job, which only runs on git tag pushes.
* Makefile: build images both with `version` and `latest`, so that they
both can be pushed to registry.
=> ci: always build Docker, tag with :tag and :latest

cmd/testops/run/create/create.go, docs/command.md
create: change store test run ID method
--
Save the test run ID to a file. You can set file path by `output` parameter or the tool will use execution path.
=> create: change store test run ID method

internal/client/clientv1.go
create: fix creation test run with environment
--
Implemented pagination in `get environment` method
=> create: fix creation test run with environment

cmd/testops/env/create/create.go, cmd/testops/run/create/create.go, internal/service/result/mocks/result.go, internal/service/result/result.go, internal/service/result/result_test.go, internal/service/run/mocks/run.go, internal/service/run/run.go, internal/service/run/run_test.go
feature: change type of parameters for the create test run command
--
Change `milestone` and `plan` types from `string` to `int64`. These parameters will take ID of entities.
---
test: update unit tests
--
Update the unit tests for `run` and `result` services
---
feature: change an output value for the create environment command
--
Change the output value for the create environment command from `ID` to `slug`
=> feature: update create test run command

internal/client/clientv1.go
feature: mark a test run as automated when created
--
This behavior will work by default for all created test runs.
=> feature: mark a test run as automated when created

docs/command.md
Add instructions how to create an environment and a milestone.
Fixed #33
=> docs: update command.md

internal/parsers/junit/junit.go
If a suite didn't contain a name, we added an empty string in place of the name. In the new version, we will skip empty suites.
=> fix: empty suites

internal/parsers/qase/qase.go
Fixed an issue with uploading Qase results to a created test run if the test run creation time is later than the test start time.
=> fix: an issue with uploading Qase result

internal/service/result/result.go
- Added a boundary check to ensure the slice end index does not exceed the length of the results array.
- Prevents runtime error when the remaining elements are fewer than the batch size.
=> fix: panic caused by out-of-range slice in batch processing

internal/parsers/allure/allure.go, internal/parsers/allure/allure_test.go
- Implemented the `extractTestOpsID` method in the `Parser` struct to extract a numeric ID from strings formatted as `name-ID`.
- Added unit tests to cover various edge cases, including invalid input, missing ID, and successful extraction.
- Improved error handling with logging for invalid ID parsing.
- Used a table-driven approach for comprehensive test coverage.
=> feat: add extractTestOpsID function with unit tests

.github/workflows/release.yml
- Configured GitHub Actions to build binaries for Linux, macOS, and Windows
- Added support for amd64 and arm64 architectures
- Automatically generates release notes and attaches compiled binaries to the GitHub release
- Ensures cross-platform compatibility for the release artifacts
#57
=> feat: add GitHub Actions pipeline for cross-platform release builds

cmd/version/version.go
- Added fallback to retrieve version from module build info when version is not provided via build flags
=> fix: display correct version when build version is not set

.github/workflows/release.yml
This pull request includes a change to the build process in the GitHub Actions workflow configuration file. The change modifies the path of the Go source file used for building the binary.
Build process modification:
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L31-R33): Changed the Go source file path from `./cmd` to `./main.go` for building the binary for different operating systems and architectures.
=> ci: change modifies the path of the Go source file used for building the binary

.github/workflows/release.yml
This pull request includes a change to the GitHub Actions workflow to define and use a tag for the app version during the build process. The most important change is the addition of a step to define the tag and the modification of the build commands to include this tag.
Changes to GitHub Actions workflow:
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R28-R37): Added a step to define the tag for the app version and modified the build commands to include the tag in the `-ldflags` option.
=> ci: use a tag for the app version during the build process

.github/workflows/release.yml
This pull request includes a small but important change to the `jobs:` section in the `.github/workflows/release.yml` file. The change corrects the order of the `-o` and `-ldflags` options in the `go build` command to ensure proper flag usage.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L35-R37): Corrected the order of the `-o` and `-ldflags` options in the `go build` command for both Windows and other operating systems.
=> ci: change corrects the order of the `-o` and `-ldflags` options in the `go build` command

.gitignore, Makefile, README.md, build/Dockerfile, cmd/root.go, cmd/testops/env/create/create.go, cmd/testops/milestone/create/create.go, cmd/testops/result/upload/upload.go, cmd/testops/run/complete/complete.go, cmd/testops/run/create/create.go, cmd/testops/run/delete/delete.go, docs/command.md, docs/source.md, internal/parsers/allure/allure.go
- Updated build configuration to generate `qasectl` as the CLI entry point
- Removed references to the old `qli` name
=> chore(cli): rename executable from `qli` to `qasectl`

cmd/testops/run/create/create.go, docs/command.md, internal/client/clientv1.go, internal/service/result/mocks/result.go, internal/service/result/result.go, internal/service/result/result_test.go, internal/service/run/mocks/run.go, internal/service/run/run.go, internal/service/run/run_test.go
- Introduced a new `--tags` flag to the `create` command for specifying tags associated with the test run.
- Updated the `CreateRun` method in the client and service layers to accept tags as a parameter.
- Modified relevant tests and mocks to accommodate the new tags functionality.
- Updated documentation to reflect the addition of the `--tags` option.
=> feat: add tags support to create run command

cmd/testops/filter/filter.go
- Introduced a new `--output` flag to the `filter` command to allow users to specify the output path for filtered results.
- Updated command functionality to support the new output option.
=> fix: add output flag to filter command for specifying output path

cmd/testops/result/upload/upload.go, docs/command.md, internal/service/result/fixture_test.go, internal/service/result/models.go, internal/service/result/result.go, internal/service/result/result_test.go
- Introduced a new `--skip-params` flag to the `upload` command to allow users to skip parameters during the upload process.
- Updated the `UploadParams` structure to include the `SkipParams` field.
- Enhanced the upload logic to clear parameters when the `skipParams` option is enabled.
- Added unit tests to verify the functionality of skipping parameters in various scenarios.
- Updated documentation to reflect the new command option and its usage.
=> feat: add skip params functionality to upload command

cmd/testops/result/upload/upload.go, docs/command.md, internal/service/result/fixture_test.go, internal/service/result/models.go, internal/service/result/result.go, internal/service/result/result_test.go
- Introduced a new `--attachment-extensions` flag to the `upload` command, allowing users to specify a comma-separated list of file extensions for attachments.
- Updated the `UploadParams` structure to include the `AttachmentExtensions` field.
- Enhanced the upload logic to filter attachments based on the specified extensions.
- Added unit tests to verify the functionality of attachment filtering in various scenarios.
- Updated documentation to reflect the new command option and its usage examples.
=> feat: add attachment filtering to upload command
